# Generated by Django 5.2 on 2025-05-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_post_image_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움')], default='normal', max_length=6),
        ),
    ]
