# Generated by Django 5.2 on 2025-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mbti',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
