# Generated by Django 5.2 on 2025-05-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='difficulty',
        ),
    ]
